server {
   listen 8070;
  
   location / {
	proxy_pass http://flask-app:5000;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-Ip $remote_addr;
        proxy_set_header X-Forwarded_For $proxy_add_x_forwarded_for;
	}
}
