services: 
  flask-app:
     build: .
     container_name: flask-app
     ports:
       - "5000:5000"
     volumes:
       - ./app:/app
     environment:
       ENVIRONMENT: Development
     restart: unless-stopped
 

  nginx-revers:
     image: nginx:latest
     container_name: nginx-revers
     ports:
       - "8070:8070"
     volumes:
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
       - flask-app
      

