metadata:
  name: user-service
  namesoace: production

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service

  minReplicas: 2
  maxReplicas: 5

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: pods
          value: 5
          periodSeconds: 60

    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: pods
          value: 1
          periodSeconds: 120

  metrics:
    - type: resource
      target:
        type: Utilization
        averageUtilization: 70
