name: Docker build and push
on:
  workflow_run:
    workflows:
      CI
    types:
      - completed
jobs:
  Docker:
    name: build and push docker image
    
    if: >
      ${{ github.event.workflow_run.conclusion == "success" &&
          github.event.workflow_run.head_branch == "master" }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - api-gateway
          - user-service
          - tassk-service
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: set up docker build
        uses: docker/setup-buildx-action@v3
      - name: build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./app/${{ matrix.service }}
          file: ./app/${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.event.workflow_run.head_sha }}
