apiVersion: apps/v1
kind: Deployment

metadata:
  name: kube-state-metrics
  namespace: monitoring

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kube-state-metrics

  template:
    metadata:
      labels:
        app: kube-state-metrics

    spec:
      serviceAccountName: kube-state-metrics

      containers:
        - name: kube-state-metrics

          image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.17.0

          ports:
            - name: http
              containerPort: 8080

            - name: telemetry
              containerPort: 8081

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 300m
              memory: 256Mi
