apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana
  namespace: monitoring

spec:
  replicas: 1

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:

      containers:

        - name: grafana

          image: grafana/grafana:12.1.0

          ports:
            - name: http
              containerPort: 3000

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 300m
              memory: 512Mi

          volumeMounts:

            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources

            - name: provider
              mountPath: /etc/grafana/provisioning/dashboards

            - name: dashboards
              mountPath: /var/lib/grafana/dashboards

      volumes:

        - name: datasource
          configMap:
            name: grafana-datasources

        - name: provider
          configMap:
            name: grafana-dashboard-provider

        - name: dashboards
          configMap:
            name: grafana-dashboard
